exp_path: ../exp/mujoco/dynamics
data_path: ../data/d4rl/
cp_path: none

# data args
num_samples: 100000
eval_ratio: 0.1
norm_obs: True
norm_rwd: False

# model args
pred_rwd: True
ensemble_dim: 7
topk: 5
hidden_dim: 200
num_hidden: 3
activation: silu
residual: True
min_std: 0.04
max_std: 1.6
decay: [0.000025, 0.00005, 0.000075, 0.000075, 0.0001]

# training args
batch_size: 256
lr: 3.e-4
grad_clip: 1000.
bootstrap: True
epochs: 500
max_epochs_since_update: 10
cp_every: 10
cp_intermediate: False